### ISSUE TITLE
Validation fails on non required fields

### ISSUE THREAD

**Issue by balintbendebimspot** [tgharold/RecursiveDataAnnotationsValidation#42]
Hey,

Cool library thanks first of all.

I have a simple dto model, generated by an xsd file. This model has different types of properties, and they use `System.ComponentModel.DataAnnotations` attributes. In case of `System.Collections.ObjectModel.Collection<string>` types the validation fails if they only have `[System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]` attribute, even though they do not have the `System.ComponentModel.DataAnnotations.RequiredAttribute()`.

In my understanding it makes totally sense to handle `MinLengthAttribute` only if the property is a `RequiredAttribute`.

Here is a sample code:
```csharp
// This is a required property and the validator works well
[System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
[System.ComponentModel.DataAnnotations.RequiredAttribute()]
[System.Xml.Serialization.XmlElementAttribute("Title", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
public string Title { get; set; }

// This has the `MinLengthAttribute` but not required, the validator fails only if it is present and the min length is less then 1
[System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
[System.Xml.Serialization.XmlElementAttribute("Priority", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
public string Priority { get; set; }

// This is handled as a required property, but it should not
[System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
[System.Xml.Serialization.XmlArrayAttribute("ReferenceLinks", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
[System.Xml.Serialization.XmlArrayItemAttribute("ReferenceLink", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
public System.Collections.ObjectModel.Collection<string> ReferenceLinks
```

Thanks very much for Your answer in advance.

Cheers,
Balint

**Comment by tgharold** [comment]
```C#
[System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
[System.ComponentModel.DataAnnotations.RequiredAttribute()]
```

Those attributes are defined by Microsoft, not in this library.  So that would be out of scope for the logic in this package.  You'll have to write your own custom attribute that combines the two concepts.
